Imported Upstream version 2.20.90-a07a4

diff --git a/tests/match-lines b/tests/match-lines
--- a/tests/match-lines
+++ b/tests/match-lines
@@ -1,6 +1,7 @@
 #!/bin/sh
-# With some versions of libpcre, apparently including 8.35,
-# the following would trigger an infinite loop in its match function.
+# Trigger a bug in the DFA matcher that would make
+# grep -F -x -o PAT print an extra newline for each match.
+# This would fail for grep-2.19 and grep-2.20.
 
 # Copyright 2014 Free Software Foundation, Inc.
 
@@ -18,16 +19,18 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 . "${srcdir=.}/init.sh"; path_prepend_ ../src
-require_timeout_
-require_en_utf8_locale_
-require_compiled_in_MB_support
-LC_ALL=en_US.UTF-8 require_pcre_
 
-printf 'a\201b\r' > in || framework_failure_
+printf 'a\n' > in || framework_failure_
 
 fail=0
 
-LC_ALL=en_US.UTF-8 timeout 3 grep -P 'a.?..b' in
-test $? = 1 || fail_ "libpcre's match function appears to infloop"
+for locale in C en_US.UTF-8; do
+  for options in -x '-E -x' '-F -x'; do
+    for o in '' -o; do
+      LC_ALL=$locale grep $o $options a in > out || fail=1
+      compare out in || fail=1
+    done
+  done
+done
 
 Exit $fail
